### ISSUE TITLE
ocr范围识别严重的效率问题

### ISSUE THREAD

**Issue by Amorter** [86maid/ddddocr#10]
![NW~9K 6B)LXI)9B{X@S{HAC](https://github.com/86maid/ddddocr/assets/63935225/b2ee6118-2264-4018-992b-268835a6d927)
![3VY0VQSU}8GK7WW1ED52C7S](https://github.com/86maid/ddddocr/assets/63935225/e7891be0-25de-49e6-b34d-b0c3a8e41226)

probability的get_text方法貌似有严重的性能问题，我看到实现好像是直接用迭代器遍历Vec，可不可以换个过滤方法，预存字符在字符集中的索引，然后set_range设置成什么字符串就直接只读取那几个索引的probability呢？

**Comment by 86maid** [comment]
已经是只遍历 set_range 了

**Comment by 86maid** [comment]
怎么做

**Comment by Amorter** [comment]
> 怎么做

暂时还没想到优化的办法，先搁置吧，等我这边项目做完我仔细研究下

**Comment by 86maid** [comment]
我改了一下，这样好点

**Comment by Amorter** [comment]
![image](https://github.com/86maid/ddddocr/assets/63935225/01893da9-551a-44e9-8c55-b181d08f4f4d)
牛逼，神医，速度优化了10倍多
