### ISSUE TITLE
ocr识别缺失

### ISSUE THREAD

**Issue by clddup** [86maid/ddddocr#17]
![code](https://github.com/86maid/ddddocr/assets/105873086/b215e838-c111-4c90-b68d-6bfc165e75d8)
![image](https://github.com/86maid/ddddocr/assets/105873086/fee611fc-c3d0-48e5-95a1-d98d4afd9ee2)
![image](https://github.com/86maid/ddddocr/assets/105873086/2e19accd-c881-4572-900b-5cb709e614ef)

识别结果为  `dp9` ,  应该是 `dpp9`

**Comment by clddup** [comment]
![image](https://github.com/86maid/ddddocr/assets/105873086/1a738a49-0655-41dd-bf87-66ff96c4e165)
![image](https://github.com/86maid/ddddocr/assets/105873086/fcb3b36b-60b7-4683-82b9-9c872303d928)

我怀疑如果连续两个内容一样, 只会识别一个

**Comment by 86maid** [comment]
两个模型都试过吗












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 下午2:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17)




 
image.png (view on web)
 image.png (view on web)
 
我怀疑如果连续两个内容一样, 只会识别一个

**Comment by clddup** [comment]
> 两个模型都试过吗 xchuang233 ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月10日(周三) 下午2:35 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17) image.png (view on web) image.png (view on web) 我怀疑如果连续两个内容一样, 只会识别一个 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

ocr 与 old 都试了,  我的启动命令是 `./ddddocr -a 0.0.0.0 -p 9898 -f`

**Comment by clddup** [comment]
@86maid 大佬有复现吗?

**Comment by 86maid** [comment]
啊这，要不你去Python那边提问?












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17)




 
@86maid 大佬有复现吗?

**Comment by clddup** [comment]
> 啊这，要不你去Python那边提问? xchuang233 ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月10日(周三) 下午4:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17) @86maid 大佬有复现吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

啊  我们这边不能解决吗, 那算了😁

**Comment by 86maid** [comment]
模型问题












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月10日(周三) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17)




  
啊这，要不你去Python那边提问? xchuang233 @.***
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年7月10日(周三) 下午4:01 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17) @86maid 大佬有复现吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
啊  我们这边不能解决吗, 那算了😁

**Comment by clddup** [comment]
> 啊这，要不你去Python那边提问? xchuang233 ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年7月10日(周三) 下午4:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [86maid/ddddocr] ocr识别缺失 (Issue #17) @86maid 大佬有复现吗? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我试了下python的, 好像没有这个问题

![image](https://github.com/user-attachments/assets/eb160664-6542-42ce-a694-643dd69507a7)

![image](https://github.com/user-attachments/assets/ed901aac-7139-49b7-bec3-0ff94824833f)


这边和python的模型有什么不一样吗

**Comment by clddup** [comment]
我去用python版的吧

**Comment by daojixing** [comment]
同样的问题，图片内容为1111，识别结果为1，
图片内容为，9996，识别未96。
