### ISSUE TITLE
跨域处理一下 大佬

### ISSUE THREAD

**Issue by netPokey** [86maid/ddddocr#4]
跨域处理一下 大佬

**Comment by 86maid** [comment]
jsonp 吗

**Comment by netPokey** [comment]
都可以呀

**Comment by 86maid** [comment]
有 jsonp 了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 跨域处理一下 大佬 (Issue #4)





 
都可以呀
