### ISSUE TITLE
ocr识别Dimensions do not match:

### ISSUE THREAD

**Issue by Amorter** [86maid/ddddocr#7]
Dimensions do not match: InputsLength { inference_input: [[1, 1, 63, 54]], model_input: [[Some(1), Some(1), Some(64), None]] }
是不是classification的缩放出问题了

**Comment by 86maid** [comment]
咋触发的












xchuang233
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月11日(周二) 凌晨3:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [86maid/ddddocr] ocr识别Dimensions do not match: (Issue #7)




 
Dimensions do not match: InputsLength { inference_input: [[1, 1, 63, 54]], model_input: [[Some(1), Some(1), Some(64), None]] }
 是不是classification的缩放出问题了

**Comment by Amorter** [comment]
![Uploading image.png…]()
let mut ocr = ddddocr::ddddocr_classification().unwrap();
        let res = ocr.classification_with_path("123.jpeg", true).unwrap();
        println!("{}", res);

**Comment by Amorter** [comment]
![image](https://github.com/86maid/ddddocr/assets/63935225/6e45c983-ba81-4569-af2b-dcdb76a39411)

let mut ocr = ddddocr::ddddocr_classification().unwrap();
        let res = ocr.classification_with_path("123.jpeg", true).unwrap();
        println!("{}", res);

**Comment by Amorter** [comment]
大佬，我试了一下，我用软件截图保存的图片能识别，然后这个图片是我用image库生成的，好像就会出上面的bug，代码如下
![image](https://github.com/86maid/ddddocr/assets/63935225/6881cf8d-18da-465a-9820-ef0b68f165af)

**Comment by Amorter** [comment]
> 大佬，我试了一下，我用软件截图保存的图片能识别，然后这个图片是我用image库生成的，好像就会出上面的bug，代码如下 ![image](https://private-user-images.githubusercontent.com/63935225/338314775-6881cf8d-18da-465a-9820-ef0b68f165af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNDc3MDksIm5iZiI6MTcxODA0NzQwOSwicGF0aCI6Ii82MzkzNTIyNS8zMzgzMTQ3NzUtNjg4MWNmOGQtMThkYS00NjVhLTk4MjAtZWYwYjY4ZjE2NWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE5MjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjOTUzNGEwODMwNTE4YjIzODk0YTExNzNmNmMyYjgwOWMxY2FlYzE0ZGJiZGFlNDUzMTM2ODY3NjdlZjQ3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UeJ7XZKGk_6AI-C6VOpb7q-hCVethwORluhpV-JrEtA)

试了以下，相同的图片python版本的ddddocr是可以识别的，rust就会报错

**Comment by Amorter** [comment]
又试了一下，确实和尺寸有关系，比如下面两张一张是65x65的就没问题，另一张67x66的就报错了
![1234](https://github.com/86maid/ddddocr/assets/63935225/afb2adc3-8e76-4c69-b668-ce7d15f86e64)
![12345](https://github.com/86maid/ddddocr/assets/63935225/505a5963-d3e4-40ab-ab63-f831fddadedf)

**Comment by Amorter** [comment]
### 一个可能的问题：
image.resize()的官网文档显示：使用指定的过滤算法调整此图像的大小。返回一个新图像。图像的宽高比被保留。图像被缩放到符合nwidth和nheight指定的边界的最大可能大小。

- “宽高比被保留”
- “最大可能大小”

67x66的图片被缩放为64x63的，是否是这个原因？

**Comment by Amorter** [comment]
> ：使用指定的过滤算法调整此图像的大小。返回一个新图像。图像的宽高比被保留。图像被缩放到符合nwidth和nheight指定的边界的最大可能大小。
> 
> * “宽高比被保留”

确定了，就是这个问题

**Comment by Amorter** [comment]
pr已提交，请查收

**Comment by 86maid** [comment]
我试试

**Comment by 86maid** [comment]
牛逼，神医！
