### ISSUE TITLE
调用slide_match()时panic   attempt to subtract with overflow

### ISSUE THREAD

**Issue by Amorter** [86maid/ddddocr#9]
有些验证码图片不会panic有些会

![bg](https://github.com/86maid/ddddocr/assets/63935225/dde1496e-9a29-4e7b-8c16-7a011ab89362)
![slice](https://github.com/86maid/ddddocr/assets/63935225/f0518769-f891-4075-8cfc-6d20b1885aaa)

**Comment by 86maid** [comment]
panic 提示什么，看看有没有搞反背景和滑块的参数顺序




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 晚上11:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
有些验证码图片不会panic有些会
 
bg.png (view on web)
 slice.png (view on web)

**Comment by Amorter** [comment]
python版本也有相同的错误

Traceback (most recent call last):
  File "d:/Projects/reverse/gt3-python-sdk/demo/flask_demo/test.py", line 15, in <module>
    res = ocr.slide_match(slice, bg)
  File "D:\DevEnvironment\anaconda3\envs\reverse\lib\site-packages\ddddocr\__init__.py", line 2661, in slide_match
    target = cv2.cvtColor(np.asarray(target), cv2.IMREAD_ANYCOLOR)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

和rust的情况差不多有的就会这样，说明好像不是rust绑定的问题，看来我issue要提到原ddddocr那边了

**Comment by 86maid** [comment]
T_T




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 晚上11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
python版本也有相同的错误
 
Traceback (most recent call last):
 File "d:/Projects/reverse/gt3-python-sdk/demo/flask_demo/test.py", line 15, in 
 res = ocr.slide_match(slice, bg)
 File "D:\DevEnvironment\anaconda3\envs\reverse\lib\site-packages\ddddocr_init_.py", line 2661, in slide_match
 target = cv2.cvtColor(np.asarray(target), cv2.IMREAD_ANYCOLOR)
 cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
 
和rust的情况差不多有的就会这样，说明好像不是rust绑定的问题，看来我issue要提到原ddddocr那边了

**Comment by 86maid** [comment]
看看&nbsp;target_image.height() 返回的是不是 0


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 晚上11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
python版本也有相同的错误
 
Traceback (most recent call last):
 File "d:/Projects/reverse/gt3-python-sdk/demo/flask_demo/test.py", line 15, in 
 res = ocr.slide_match(slice, bg)
 File "D:\DevEnvironment\anaconda3\envs\reverse\lib\site-packages\ddddocr_init_.py", line 2661, in slide_match
 target = cv2.cvtColor(np.asarray(target), cv2.IMREAD_ANYCOLOR)
 cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
 
和rust的情况差不多有的就会这样，说明好像不是rust绑定的问题，看来我issue要提到原ddddocr那边了

**Comment by Amorter** [comment]
我知道了，ddddocr的边缘检测会获取每一个像素的颜色，判断颜色的范围。python版本的判断之前有一个!src.empty()的断言，这个rust版本也加了一个unreachable!()的断言
![image](https://github.com/86maid/ddddocr/assets/63935225/8f10f6bb-a04b-48ad-bc92-a6d6e56d53b6)
我裁剪图片的时候不小心少裁剪了一行像素，导致有些图片缺口部分有透明像素，并且我是用PNG编码保存的，透明像素被保存下来了。然后ddddocr断言的时候就成空了.....话说png转换成Vec<8>居然tmd能变成空或者范围外的东西？？？

建议要不要加一层统一把图片变成JPG的转化或者过滤下异常像素？这样直接能解决原dddocr项目中的问题

**Comment by Amorter** [comment]
> 我知道了，ddddocr的边缘检测会获取每一个像素的颜色，判断颜色的范围。python版本的判断之前有一个!src.empty()的断言，这个rust版本也加了一个unreachable!()的断言 ![image](https://private-user-images.githubusercontent.com/63935225/339041663-8f10f6bb-a04b-48ad-bc92-a6d6e56d53b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDc4MDksIm5iZiI6MTcxODIwNzUwOSwicGF0aCI6Ii82MzkzNTIyNS8zMzkwNDE2NjMtOGYxMGY2YmItYTA0Yi00OGFkLWJjOTItYTZkNmU1NmQ1M2I2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE1NTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWU3NTE2ZmQ3MThiYTBjOWE2ZWU5NDkyYmQzZTYyYTIwN2I5OThlODNkNDUyOTM2MGQ5OGU4MDdhOWExZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrLx2063D0rIPSUXE6QGDriUWK9UigZG1diEI8x0d5Y) 我裁剪图片的时候不小心少裁剪了一行像素，导致有些图片缺口部分有透明像素，并且我是用PNG编码保存的，透明像素被保存下来了。然后ddddocr断言的时候就成空了.....话说png转换成Vec<8>居然tmd能变成空或者范围外的东西？？？
> 
> 建议要不要加一层统一把图片变成JPG的转化或者过滤下异常像素？这样直接能解决原dddocr项目中的问题

好像不是这个问题。。。。我修复后在其他实例还是出现了相同的问题

**Comment by 86maid** [comment]
但我看到的恐慌位置是&nbsp;\imageproc-0.23.0\src\edges.rs:63




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月12日(星期三) 晚上11:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
我知道了，ddddocr的边缘检测会获取每一个像素的颜色，判断颜色的范围。python版本的判断之前有一个!src.empty()的断言，这个rust版本也加了一个unreachable!()的断言
 image.png (view on web)
 我裁剪图片的时候不小心少裁剪了一行像素，导致有些图片缺口部分有透明像素，并且我是用PNG编码保存的，透明像素被保存下来了。然后ddddocr断言的时候就成空了.....话说png转换成Vec<8&gt;居然tmd能变成空或者范围外的东西？？？
 
建议要不要加一层统一把图片变成JPG的转化或者过滤下异常像素？这样直接能解决原dddocr项目中的问题

**Comment by Amorter** [comment]
![image](https://github.com/86maid/ddddocr/assets/63935225/fecd75e4-2f20-4a58-873e-b43ff19ce4c1)
你是dui'de对的

**Comment by Amorter** [comment]
![image](https://github.com/86maid/ddddocr/assets/63935225/05244029-2e57-43b1-b031-2f8eb713eb63)
这一步的height还是正常的
![image](https://github.com/86maid/ddddocr/assets/63935225/f624c717-3fda-4c00-8d93-e0f67d31e125)
进入到canny内就变成0了，这是什么原因？

**Comment by 86maid** [comment]
这里是 0，而且你调试的变量错了。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
image.png (view on web)
 这一步的height还是正常的
 image.png (view on web)
 进入到canny内就变成0了，这是什么原因？

**Comment by Amorter** [comment]
> 且你调试的变

对不起，眼瞎了，我再跟踪下

**Comment by Amorter** [comment]
> 这里是 0，而且你调试的变量错了。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "86maid/ddddocr" ***@***.***&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic attempt to subtract with overflow (Issue #9) image.png (view on web) 这一步的height还是正常的 image.png (view on web) 进入到canny内就变成0了，这是什么原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

大佬，我这边用不panic的样例测试，进入到canny之后height就已经不是0了哇

**Comment by 86maid** [comment]
你看看这个地方，这个是判断像素的透明通道的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





  
这里是 0，而且你调试的变量错了。。。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "86maid/ddddocr" @.&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic attempt to subtract with overflow (Issue #9) image.png (view on web) 这一步的height还是正常的 image.png (view on web) 进入到canny内就变成0了，这是什么原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
大佬，我这边用不panic的样例测试，进入到canny之后height就已经不是0了哇

**Comment by Amorter** [comment]
> 你看看这个地方，这个是判断像素的透明通道的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "86maid/ddddocr" ***@***.***&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:11 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic attempt to subtract with overflow (Issue #9) 这里是 0，而且你调试的变量错了。。。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "86maid/ddddocr" @.&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 凌晨0:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic attempt to subtract with overflow (Issue #9) image.png (view on web) 这一步的height还是正常的 image.png (view on web) 进入到canny内就变成0了，这是什么原因？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 大佬，我这边用不panic的样例测试，进入到canny之后height就已经不是0了哇 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，我理解您的意思了

**Comment by Amorter** [comment]
您好，我debug了很久还是不清楚问题出在哪
于是我找到了有关ddddocr的一个issue，好像和这个问题有点关系
https://github.com/sml2h3/ddddocr/issues/163

**Comment by 86maid** [comment]
嘿，我好像修好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "86maid/ddddocr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 凌晨3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [86maid/ddddocr] 调用slide_match()时panic   attempt to subtract with overflow (Issue #9)





 
您好，我debug了很久还是不清楚问题出在哪
 于是我找到了有关ddddocr的一个issue，好像和这个问题有点关系
 sml2h3/ddddocr#163

**Comment by 86maid** [comment]
试试

**Comment by Amorter** [comment]
> 试试

好的

**Comment by Amorter** [comment]
牛逼，神医
